global:
  scrape_timeout: 15s
  scrape_interval: 30s
  evaluation_interval: 15s


alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - alertmanager:9093  # Uncomment when alertmanager is added

rule_files:
  # - 'alert.rules'  # Add rule files if needed

otlp:
  promote_resource_attributes:
    - service.instance.id
    - service.name
    - service.namespace
    - cloud.availability_zone
    - cloud.region
    - container.name
    - deployment.environment.name

storage:
  tsdb:
    out_of_order_time_window: 30m

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
    metrics_path: /metrics

  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
    metrics_path: /metrics

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: /metrics
    scheme: http
    basic_auth:
      # Just a dev admin
      username: admin
      password: admin
