# Generated by Django 5.2.4 on 2025-07-10 07:06

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_user_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=255)),
                ('verified_domain', models.SlugField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_received_at', models.DateTimeField(auto_now_add=True, help_text='The time we received the email')),
                ('event', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('soft_bounce', 'Soft Bounce'), ('hard_bounce', 'Hard Bounce'), ('unsubscribe', 'Unsubscribe'), ('spam', 'Spam')], default='sent', max_length=16)),
                ('event_time', models.DateTimeField(help_text='The time the event was registered by the provider')),
                ('send_time', models.DateTimeField(help_text='The time the email was sent, according to the provider')),
                ('message_id', models.CharField(help_text='The unique id from the sender.', max_length=255)),
                ('from_address', models.EmailField(max_length=254)),
                ('recipients', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), size=None)),
                ('username', models.CharField(help_text='Some providers tell use the smtp username', max_length=255, null=True)),
                ('reason', models.TextField(help_text='Some events might have a reason', null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mailer.smtpprovider')),
            ],
        ),
        migrations.CreateModel(
            name='EmailProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='Use it to query the provider for the app smtp credentials', max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.deployedapp')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mailer.smtpprovider')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('app', 'provider'), name='unique_app_smtp_provider'), models.UniqueConstraint(condition=models.Q(('active', True)), fields=('app',), name='unique_active_app_smtp_provider')],
            },
        ),
    ]
