# Generated by Django 5.2.4 on 2025-07-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_plan'),
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailprovider',
            name='from_address',
            field=models.EmailField(default='unknown@nowhere.com', max_length=254),
        ),
        migrations.AddConstraint(
            model_name='emailprovider',
            constraint=models.UniqueConstraint(fields=('provider', 'from_address'), name='unique_provider_from_address'),
        ),
    ]
