# Generated by Django 5.2.4 on 2025-07-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('mailer', '0003_emailprovider_maxed_quota'), ('mailer', '0004_remove_emailprovider_maxed_quota_and_more')]

    dependencies = [
        ('mailer', '0002_emailprovider_from_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailprovider',
            name='maxed_quota_for',
            field=models.DateField(help_text='The billing cycle for which the quota was maxed', null=True),
        ),
    ]
