# Generated by Django 5.2.4 on 2025-07-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_emailprovider_from_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailprovider',
            name='maxed_quota',
            field=models.BooleanField(default=False),
        ),
    ]
