# Generated by Django 5.2.3 on 2025-06-29 11:22

from django.db import migrations
from core.models import PlanEnum

class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_deployedapp"),
    ]

    operations = [
        migrations.RunSQL(
            sql=f"""CREATE TYPE plan AS ENUM ('{"', '".join(PlanEnum.values)}');""",
            reverse_sql="DROP TYPE plan;",
        ),
    ]
