# Generated by Django 5.2.3 on 2025-06-29 12:32

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=core.fields.PlanField(default='hobby'),
        ),
    ]
